apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: The infra team
spec:
  type: team
  profile:
    displayName: Infrastructure
  children:
  - default
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: development
  description: The development team
spec:
  type: team
  profile:
    displayName: Development
  children:
  - default
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates
  description: list of available templates
spec:
  targets:
  - ./oci-static-page/template.yaml
  - ./oci-oke-cluster/template.yaml